import SideBar from '../components/SideBar';
import "./globals.css";
import { SessionProvider } from "../components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextAuth]";
import Login from "@/components/Login";

export const metadata = {
  title: "Chat GPT",
  description: "Generated by ChatGPT",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <SessionProvider session={session}>
        {!session ? (
          <Login />
        ) : (
          <body className="flex">
            <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
              <SideBar />
            </div>
            <div>Client Provider Notiiffiction</div>
            <div className="bg-[#343541] flex-1">{children}</div>
          </body>
        )}
      </SessionProvider>
    </html>
  );
}
